// AUTH ACTIONS

export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// STORE DATA

export const SET_STORES_DATA = "SET_STORES_DATA";