// AUTH ACTIONS

export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// STORE DATA

export const SET_STORES_DATA = "SET_STORES_DATA";
export const CLEAR_STORES_DATA = "CLEAR_STORES_DATA";
export const SET_CITIES_DATA = "SET_CITIES_DATA";
export const SET_FLAGS_DATA = "SET_FLAGS_DATA";
export const SET_LOCAL_STORES_DATA = "SET_LOCAL_STORES_DATA";
